### ISSUE TITLE
Actualizar la imagen de docker para montarla con un docker compose y cogiendo la imagen de go que tiene hot-reload.

### ISSUE THREAD

**Issue by dtote** [fullstacktf/order-food-backend#26]
- [Repositorio de ayuda](https://github.com/manolors/docker-golang-hot-reload)

Esto se está implementando en [esta rama](https://github.com/fullstacktf/order-food-backend/tree/fix/docker-builds) y hemos conseguido que haciendo ```make``` nos levante tanto el mongo como el server y el debuger del server (que funciona como un nodemon). El problema es que no sabemos si lo estamos haciendo bien, porque por ejemplo el server no podemos entrar a él, es decir en localhost:3000 debería atendernos, pero no lo hace, sin embargo dice que funciona bien supuestamente.

No sé si @raulanatol o @manolors podrán echarle un ojo por encima a ver si ven algo raro o probarlo 😥

**Comment by raulanatol** [comment]
@dtote comentamos hoy en clase 🤘
